
task:
  alias: Tests
  container:
    dockerfile: .ci/Dockerfile
    cpu: 8
    memory: 16G
  upgrade_script:
    - flutter channel master
    - flutter upgrade
    - git fetch origin master
  activate_script: pub global activate flutter_plugin_tools
  matrix:
    - name: test
      test_script:
        - flutter doctor
    - name: test 2
      test_script:
        - flutter doctor
    - name: test 3
      test_script:
        - flutter doctor

# task:
#   depends_on: Tests
#   container:
#     dockerfile: .ci/Dockerfile
#     cpu: 8
#     memory: 16G
#   upgrade_script:
#     - flutter channel master
#     - flutter upgrade
#     - git fetch origin master
#   activate_script:
#     - pub global activate --source path ./packages/melos
#     - export PATH="$PATH":"$HOME/.pub-cache/bin"
#     - melos bootstrap --ignore="*example*"
#   matrix:
#     - name: melos_analyze
#       test_script:
#         - git config --global user.email "ychris@google.com"
#         - git config --global user.name "plugin_team"
#         - export PATH="$PATH":"$HOME/.pub-cache/bin"
#         - melos run update_version
#         - git branch
#         - git status
#         - git log
#         - git push --follow-tags



