name: release
on:
  push:
    branches:
      - master

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Log git sha
        run: echo "${{ github.sha }} ${{ github.sha }}~"
      - name: Log event
        run: echo ${{ toJSON(github.event) }}
      - name: Log run_number
        run: echo ${{ github.run_number }}
      - name: Wait on tests
        # or lewagon/wait-on-check-action@v0.2 for most recent stable version
        uses: lewagon/wait-on-check-action@bafe56a6863672c681c3cf671f5e10b20abf2eaa
        with:
          ref: ${{ github.sha }} # can be commit SHA or tag too
          running-workflow-name: 'release'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10 # seconds
      - name: Wait on last commit
        # or lewagon/wait-on-check-action@v0.2 for most recent stable version
        uses: lewagon/wait-on-check-action@bafe56a6863672c681c3cf671f5e10b20abf2eaa
        with:
          ref: ${{ github.sha }}~ # can be commit SHA or tag too
          check-name: 'release'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10 # seconds
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          fetch-depth: 0 #fetch all history so the tool can get all the tag to determine version.

      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: git config user.name
        run: git config --global user.name ${{ secrets.USER_NAME }}
      - name: git config user.email
        run: git config --global user.email ${{ secrets.USER_EMAIL }}
      - name: run release
        run: echo "replace this command with release command"
      - name: sleep
        run: sleep 60


      # - name: "Bootstrap Workspace"
      #   run: melos bootstrap --ignore="*example*"
      # - name: Melos Version
      #   run: melos version --yes
      # - name : log
      #   run: git log
      # - name: git push
      #   run: git push --follow-tags

      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     branch-suffix: release-packages
      #     delete-branch: true
      #     title: 'chore(release): publish packages'

        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
